
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_AXI_IIC_FMC_DEVICE_ID,
		XPAR_AXI_IIC_FMC_BASEADDR,
		XPAR_AXI_IIC_FMC_TEN_BIT_ADR,
		XPAR_AXI_IIC_FMC_GPO_WIDTH
	},
	{
		XPAR_AXI_IIC_MAIN_DEVICE_ID,
		XPAR_AXI_IIC_MAIN_BASEADDR,
		XPAR_AXI_IIC_MAIN_TEN_BIT_ADR,
		XPAR_AXI_IIC_MAIN_GPO_WIDTH
	}
};


